name: Node.js Package

on:
    release:
        types: [created]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 15
            - run: npm ci
            - run: npm test
    
    publish-npm:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Build
              uses: actions/checkout@v3
              uses: actions/setup-node@v3
              with:
                node-version: 15
                registry-url: "https://registry.npmjs.org"
              run: |
                npm ci
                npm run build
            - name: Publish
              shell: bash
              run: env
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

